In [2]:
import pandas as pd
import numpy as np

In [55]:
pd.options.display.float_format = '{:.2f}'.format

In [5]:
np.set_printoptions(precision=2)

In [11]:
# generando una matriz e 2 x 5 con numeros aleatorios
x1 = np.random.rand(2,5) * 10
x1

array([[8.37, 5.79, 8.18, 8.06, 5.44],
       [0.19, 4.53, 3.31, 0.7 , 2.93]])

In [12]:
x2 = np.random.rand(2,5) * -1
x2

array([[-0.26, -0.68, -0.75, -0.11, -0.43],
       [-0.93, -0.46, -0.35, -0.62, -0.57]])

**Concatenar ambas matrices con numpy**

In [29]:
x1[0]

array([8.37, 5.79, 8.18, 8.06, 5.44])

In [16]:
np.concatenate([x1,x2]).shape

(4, 5)

In [19]:
# Concatenar en eje columnas
np.concatenate([x1,x2], axis=1).shape

(2, 10)

**Concatenar ambas matrices con pandas como Series**

In [57]:
s1 = pd.Series(x1[0], index = ['a', 'b', 'c', 'd', 'e'])
s1

a   8.37
b   5.79
c   8.18
d   8.06
e   5.44
dtype: float64

In [58]:
s2 = pd.Series(x2[0], index = ['c', 'd', 'e', 'f', 'g',])
s2

c   -0.26
d   -0.68
e   -0.75
f   -0.11
g   -0.43
dtype: float64

In [59]:
pd.concat([s1,s2])

a    8.37
b    5.79
c    8.18
d    8.06
e    5.44
c   -0.26
d   -0.68
e   -0.75
f   -0.11
g   -0.43
dtype: float64

In [60]:
pd.concat([s1,s2], axis=1)

0     1
a 8.37   nan
b 5.79   nan
c 8.18 -0.26
d 8.06 -0.68
e 5.44 -0.75
f  nan -0.11
g  nan -0.43

In [61]:
s1.reset_index(drop=True)

0   8.37
1   5.79
2   8.18
3   8.06
4   5.44
dtype: float64

In [64]:
pd.concat([s1.reset_index(drop=True),s2.reset_index(drop=True)], axis=1)

0     1
0 8.37 -0.26
1 5.79 -0.68
2 8.18 -0.75
3 8.06 -0.11
4 5.44 -0.43

**Concatenar Dataframes**

In [68]:
df1 = pd.DataFrame(np.random.rand(3,2)*10,columns=['a','b'])
df1

a    b
0 2.03 5.85
1 1.81 9.52
2 6.61 9.11

In [69]:
df2 = pd.DataFrame(np.random.rand(3,2)*10,columns=['a','b'], index=[2,3,4])
df2

a    b
2 3.65 0.96
3 3.00 2.73
4 0.59 7.94

In [70]:
pd.concat([df1,df2])

a    b
0 2.03 5.85
1 1.81 9.52
2 6.61 9.11
2 3.65 0.96
3 3.00 2.73
4 0.59 7.94

In [71]:
# Concatenar  a lo largo de las columnas
pd.concat([df1,df2], axis=1)

a    b    a    b
0 2.03 5.85  nan  nan
1 1.81 9.52  nan  nan
2 6.61 9.11 3.65 0.96
3  nan  nan 3.00 2.73
4  nan  nan 0.59 7.94

In [75]:
# Utilizando concat con joins
pd.concat([df1,df2], axis=1, join='inner')

a    b    a    b
2 6.61 9.11 3.65 0.96

In [79]:
# Borrando los indices
pd.concat([df1.reset_index(drop=True),
          df2.reset_index(drop=True)
          ], axis=1)

a    b    a    b
0 2.03 5.85 3.65 0.96
1 1.81 9.52 3.00 2.73
2 6.61 9.11 0.59 7.94

**Usando append**

In [81]:
df1.append(df2)

a    b
0 2.03 5.85
1 1.81 9.52
2 6.61 9.11
2 3.65 0.96
3 3.00 2.73
4 0.59 7.94

In [82]:
df1.append(df2).append(df2)

a    b
0 2.03 5.85
1 1.81 9.52
2 6.61 9.11
2 3.65 0.96
3 3.00 2.73
4 0.59 7.94
2 3.65 0.96
3 3.00 2.73
4 0.59 7.94

In [83]:
# Unir a traves del eje de las columnas usando la Transpuesta
df1.T.append(df2.T)

0    1    2    3    4
a 2.03 1.81 6.61  nan  nan
b 5.85 9.52 9.11  nan  nan
a  nan  nan 3.65 3.00 0.59
b  nan  nan 0.96 2.73 7.94

In [84]:
df1

a    b
0 2.03 5.85
1 1.81 9.52
2 6.61 9.11