In [2]:
10+3

13

In [3]:
2*3

6

In [4]:
2**3

8

In [5]:
x = 12
x

12

In [6]:
y = 15

In [7]:
x + y

27

In [8]:
'Hola mundo'

'Hola mundo'

In [9]:
x = 'Hola'
y = 'Mundo'
x + y

'HolaMundo'

In [10]:
x +  ' ' +  y

'Hola Mundo'

In [11]:
[1,2,3,5,6]

[1, 2, 3, 5, 6]

In [12]:
[1,2,3,4] + [2,3,4]

[1, 2, 3, 4, 2, 3, 4]

In [13]:
lista = [1,2,3,4,5]

In [14]:
lista[0]

1

In [15]:
lista[2]

3

In [16]:
lista[-1]

5

In [17]:
[1,2,3,4,5] + [10]

[1, 2, 3, 4, 5, 10]

In [18]:
import numpy as np

In [19]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [20]:
np.array([1,2,3,4,5]) + 10

array([11, 12, 13, 14, 15])

In [21]:
np.array([1,2,3,4,5]).shape

(5,)

In [22]:
np.array([[1,2,3,4],[6,7,8,9]])

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [23]:
np.array([[1,2,3,4],[6,7,8,9]]).shape

(2, 4)

In [24]:
np.array([[1,2,3,4],[6,7,8,9]])[0]

array([1, 2, 3, 4])

In [25]:
np.array([[1,2,3,4],[6,7,8,9]])[0][2]

3

In [27]:
import pandas as pd

In [28]:
pd.Series([10,9,8,7,6])

0    10
1     9
2     8
3     7
4     6
dtype: int64

In [29]:
#Creando una Pandas Series
sr = pd.Series([10,9,8,7,6])
sr

0    10
1     9
2     8
3     7
4     6
dtype: int64

In [30]:
#Obteniendo sus valores
sr.values

array([10,  9,  8,  7,  6])

In [31]:
#Obteniendo el rango (inicio, fin, pasos)
sr.index

RangeIndex(start=0, stop=5, step=1)

In [32]:
#la forma de la series
sr.shape

(5,)

In [33]:
# Acceder a un elemento
sr[3]

7

In [35]:
# Acceder a informacion por medio de los indices
sr[[0,4,2]]

0    10
4     6
2     8
dtype: int64

In [38]:
# Definiendo un nuevo indice para la columna index
sr = pd.Series([10,9,8,7,6], index = ['a','b','c','d','e'])
sr

a    10
b     9
c     8
d     7
e     6
dtype: int64

In [39]:
# acceder a valores con los nuevos indices
sr['c']

8

In [40]:
# acceder a valores con los nuevos indices
sr[['c','d','e']]

c    8
d    7
e    6
dtype: int64

In [41]:
# Usando notacion de slices para valores en un rango
sr['b':'e']

b    9
c    8
d    7
e    6
dtype: int64

In [44]:
# creando un diccionario
dict_data = {'CO':100,'MX':200,'AR':300}
dict_data

{'AR': 300, 'CO': 100, 'MX': 200}

In [45]:
# Accediendo a los valores
dict_data.keys()

dict_keys(['CO', 'MX', 'AR'])

In [46]:
# Accediendo a un valor puntual
dict_data['MX']

200

In [47]:
# convirtiendo el dicionario en un Pandas Series
pd.Series(dict_data)

CO    100
MX    200
AR    300
dtype: int64

In [48]:
pd.Series(dict_data, index=['CO','MX','PE'])

CO    100.0
MX    200.0
PE      NaN
dtype: float64

In [49]:
import numpy as np

In [56]:
# el objeto Not a Number,un valor nulo
np.nan

nan

In [51]:
np.nan + 10

nan

In [58]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [52]:
np.nan * 10

nan

In [53]:
sr = pd.Series(dict_data, index=['CO','MX','PE'])
sr

CO    100.0
MX    200.0
PE      NaN
dtype: float64

In [54]:
sr.isnull()

CO    False
MX    False
PE     True
dtype: bool

In [55]:
sr.notnull()

CO     True
MX     True
PE    False
dtype: bool